services:
  mojimili-laravel:
    labels:
      - traefik.enable=true
      - traefik.http.routers.mojimili.rule=Host(`${DOMAIN_NAME}`)
      ## || Host(`www.${DOMAIN_NAME}`)
      - traefik.http.routers.mojimili.entrypoints=websecure
      - traefik.http.routers.mojimili.tls=true
      - traefik.http.routers.mojimili.tls.certresolver=${CERT_RESOLVER:-le}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
